### ISSUE TITLE
Update 1.21

### ISSUE THREAD

**Issue by NorthernChicken** [Darkhax-Minecraft/Shield-Banner-Fix#1]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Feedback

I don't think it would be that hard since nothing about shields or banners were changed in the update.

**Comment by Darkhax** [comment]
Hello, a 1.21 port is planned but I do not have an ETA. This update should be pretty easy but it's not true that nothing with shields or banners have changed. Mojang moved banner patterns to a datapack registry and added several new patterns to the game. 

Here is my statement on 1.21 from Discord.

![image](https://github.com/Darkhax-Minecraft/Shield-Banner-Fix/assets/2250798/822af47d-6eea-4845-b7e2-887163f8e029)
